eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心地址
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/ #多个配置中心
spring:
  application:
    name: eureka-client
server:
  port: 8080